name: Run main.py every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  run-main-py:
    name: Run main.py
    runs-on: ubuntu-latest

    env:
      LEMMY_USERNAME: ${{ secrets.LEMMY_USERNAME }}
      LEMMY_PASSWORD: ${{ secrets.LEMMY_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py
      env:
        LEMMY_USERNAME: ${{ secrets.LEMMY_USERNAME }}
        LEMMY_PASSWORD: ${{ secrets.LEMMY_PASSWORD }}
